spring:
  application:
    name: '@project.artifactId@'
  datasource:
    url: jdbc:h2:mem:testDb
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  jackson:
    serialization:
      fail-on-empty-beans: false

constants:
  error:
    manufacturerNotFoundException:
      code: MANUFACTURER_DETAILS_NOT_FOUND
      message: 'Manufacturer data is not present.'
    constraintViolationException:
      code: INVALID_DETAILS
      message: 'Invalid details provided in the request.'
    dataIntegrityViolationException:
      code: DUPLICATE_MANUFACTURER_NAME
      message: 'Please provide unique Manufacturer name.'

server:
  servlet:
    context-path: /catalogue